version: '3.8'

services:
  # 🗄️ MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # 🧰 phpMyAdmin (web UI for MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - mysql

  # 🚀 Laravel backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    restart: always
    volumes:
      - ./backend:/var/www
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis

  # 💻 Vue frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue
    restart: always
    volumes:
       - ./frontend:/app
       - /app/node_modules
    depends_on:
      - backend

  # 🌐 Nginx server
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  # 🔴 Redis (cache, queue, session)
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
